version: "3.7"

services:
  lies-counter:
    container_name: lc_server
    build:
      context: .
      dockerfile: _docker/Dockerfile
    expose:
      - "8080"
    depends_on:
      - redis

  redis:
    container_name: lc_redis
    image: redis:5.0.7
